import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="flex flex-col items-center h-screen w-screen">
          {/* <div className="w-full h-1/6 border-2">
            Navbar
          </div> */}
          <div className="w-1/2 h-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
